Store/Mivla/urls.py
from django.contrib import admin
from django.urls import path, include
from products.views import index, products
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Store/users/urls.py
from django.urls import path
from .views import login, register, profile, logout


app_name = 'users'
urlpatterns = [
    path('registrer/', register, name='register'),
    path('login/', login, name='login'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout')

]

Store/products/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images')
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'Продукт: {self.name} | Категория {self.category}'

Store/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)

Store/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from .models import User
from django import forms


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs=
                                                      {'class': 'form-control py-4',
                                        'placeholder':"Введите имя пользователя"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control py-4',
                                                            'placeholder':"Введите пароль"}))

    class Meta:
        name = User
        fields = ('username', 'password')


class UserRegForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    first_name = forms.CharField(widget=forms.TextInput(attrs=
                                                      {'class': 'form-control py-4',
                                                       'placeholder': "Введите имя"}))

    last_name = forms.CharField(widget=forms.TextInput(attrs=
                                                        {'class': 'form-control py-4',
                                                         'placeholder': "Введите фамилию"}))

    username = forms.CharField(widget=forms.TextInput(attrs=
                                                        {'class': 'form-control py-4',
                                                         'placeholder': "Введите имя пользователя"}))
    email = forms.CharField(widget=forms.EmailInput(attrs=
                                                      {'class': 'form-control py-4',
                                                       'placeholder': "Введите адрес почты"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control py-4',
                                                                 'placeholder': "Введите пароль"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control py-4',
                                                                 'placeholder': "Подтвердите пароль"}))


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = fields = ('first_name', 'last_name', 'username', 'email')

    first_name = forms.CharField(widget=forms.TextInput(attrs=
                                                        {'class': 'form-control py-4',
                                                         }))

    last_name = forms.CharField(widget=forms.TextInput(attrs=
                                                       {'class': 'form-control py-4',
                                                       }))

    username = forms.CharField(widget=forms.TextInput(attrs=
                                                      {'class': 'form-control py-4', 'readonly': True
                                                       }))
    email = forms.CharField(widget=forms.EmailInput(attrs=
                                                    {'class': 'form-control py-4', 'readonly': True
                                                     }))



Store/products/views.py
from django.shortcuts import render
from .models import Category, Product


def index(request):
    context = {'title': 'Main title'}
    return render(request, template_name='products/index.html', context=context)


def products(request):
    context = {'title': 'Title',
            'products': Product.objects.all(),
            'category': Category.objects.all()}
    return render(request, template_name='products/products.html', context=context)

Store/users/views.py
from django.contrib import auth, messages
from django.shortcuts import render, HttpResponseRedirect
from .models import User
from .forms import UserLoginForm, UserRegForm, UserProfileForm


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect('/')
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)


def register(request):
    if request.method == 'POST':
        form = UserRegForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Вы зарегистрировались!')
            return HttpResponseRedirect('/')
    else:
        form = UserRegForm()
    context = {'form': form}
    return render(request, 'users/register.html', context)


def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            return 1
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance=request.user)
    context = {'title': 'Я каменщик', 'form': form}
    return render(request, 'users/profile.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')


Store/products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}


</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if user.is_authenticated%}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a>
                        </li>
                        <li><a class="dropdown-item" href="orders/orders.html">Заказы</a></li>
                        {% if user.is_superuser % or user.is_staff %}
                        <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админ-панель</a></li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'users:logout' %}">
                                Выйти
                            </a>
                        </li>
                    </ul>
                </li>
                {% else %}
                     <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %} {% endblock %}

{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="/static/vendor/jquery/jquery.min.js"></script>
<script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="/static/vendor/fontawesome/fontawesome-icons.js" crossorigin="anonymous"></script>

</body>

</html>

Store/products/templates/products/index.html
{% extends 'products/base.html' %}


{% block css %}
    <link href="vendor/css/index.css" rel="stylesheet">
{% endblock %}

{% block content %}
<section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">Store</h1>
                <p>
                    Новые образы и лучшие бренды на Store.
                    Бесплатная доставка по всему миру!
                    Аутлет: до -70% Собственный бренд. -20% новым покупателям!
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:index' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}


Store/products/templates/products/products.html
{% extends 'products/base.html' %}

{% block css %}
    <link href="vendor/css/products.css" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Store</h1>
            <div class="list-group">
                {% for category in category %}
                    <a href="#" class="list-group-item">{{category.name}}</a>
                {% endfor %}
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

            <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="vendor/img/slides/slide-1.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="vendor/img/slides/slide-2.jpg" alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="vendor/img/slides/slide-3.jpg" alt="Third slide">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

            <div class="row">
                {% for product in products %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="#">
                            <img class="card-img-top"
                                 src={{product.image.url}}
                                 alt="">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="#">{{product.name}}</a>
                            </h4>
                            <h5>{{product.price}},00 руб.</h5>
                            <p class="card-text">{{product.desc}}</p>
                        </div>
                        <div class="card-footer text-center">
                            <button type="button" class="btn btn-outline-success">Отправить в корзину</button>
                        </div>
                    </div>
                </div>

                {% endfor %}

            </div>

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            </nav>

        </div>

    </div>

</div>
{% endblock %}

{% block footer %}
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Store 2022</p>
    </div>
    <!-- /.container -->
</footer>
{% endblock %}


Store/users/templates/users/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Store - Регистрация</title>
    <link href="{% static 'vendor/css/auth.css'%}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        {% block content %}
        {% endblock %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'vendor/js/auth.js'%}"></script>
</body>
</html>

Store/users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                            {% if messages or form.non_field_errors %}

                            <div class="alert {% if messages} alert-success {% else %} alert-warning{% endif %} alert-dismissible fade show" role="alert"
                                style="margin-top: 50px;">
                                {% if messages %}
                                {% for message in messages %}
                                    {{ message}}
                                {% endfor %}
                                {% else %}
                                    {{ form.non_field_errors}}
                                {% endif %}

                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                             </div>
                            {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'users:login' %}" method='post'>
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                        {{ form.username }}
                                    </div>
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                                        {{ form.password }}
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="small" href="#">Забыли пароль?</a>
                                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a href="#">
                                            <i class="fab fa-google fa-2x" style="color: #d9503e;"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fab fa-vk fa-2x" style="color: #4a658b;"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fab fa-github fa-2x" style="color: #303030;"></i>
                                        </a>
                                        <a href="#">
                                            <i class="fab fa-facebook fa-2x" style="color: #405794;"></i>
                                        </a>
                                    </div>
                                </form>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{%url 'users:register'%}">Нужен аккаунт? Зарегистрируйся!</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock %}

Store/users/templates/users/profile.html
{% extends 'products/base.html' %}


{% block css %}
   <link href="../vendor/css/profile.css" rel="stylesheet">
{% endblock %}

{% block contnent %}
<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Профиль</h4>
            <div class="col-lg-12 text-center">
                <img width="100" height="100"
                     src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22200%22%20height%3D%22200%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20200%20200%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1765bc6c014%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A10pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1765bc6c014%22%3E%3Crect%20width%3D%22200%22%20height%3D%22200%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2274.421875%22%20y%3D%22104.65%22%3E200x200%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
                     class="img-thumbnail">
            </div>
            <form action="{% url 'users:profile'%}" method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                           <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                    </div>
                </div>

                <div class="form-row">
                    <div class="col-lg-6">
                         <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.email.id_for_label }}">
                                Адрес электронной почты
                            </label>
                            {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-5">
            <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
                Корзина <span class="badge badge-secondary badge-pill">3</span>
            </h4>
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">Product name</h5>
                    <p class="card-text">Product description</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="basketID" type="number" class="form-control"
                                       value="1" min="0">
                            </div>
                            <div class="col-lg-4">2 390 руб.</div>
                            <div class="col-lg-4">
                                <a href="#">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="card mb-3">
                <div class="card-footer">
                    <p class="float-left">Итого</p>
                    <h4 class="float-right">2 390 руб.</h4>
                </div>
            </div>
            <a class="btn btn-success btn-lg float-right" href="../orders/order-create.html">
                Оформить заказ
            </a>
        </div>
    </div>
</div>
{% endblock %}

Store/users/templates/users/register.html
{% extends 'users/base.html' %}

{% block content %}
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {{ form.errors }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                            </div>
                            <div class="card-body">
                                 <form action="{% url 'users:register' %}" method='post'>
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{form.first_name.id_for_label }}">Имя</label>
                                               {{ form.first_name}}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{form.last_name.id_for_label }}">Фамилия</label>
                                                {{ form.last_name }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{form.username.id_for_label }}">Имя пользователя</label>
                                            {{ form.username }}
                                        </div>
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{form.email.id_for_label }}">Адрес электронной
                                                почты</label>
                                            {{ form.email}}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{form.password1.id_for_label }}">Пароль</label>
                                                {{ form.password1 }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{form.password2.id_for_label }}">Подтверждение
                                                    пароля</label>
                                                {{ form.password2 }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mt-4 mb-0">
                                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{%url 'users:login'%}">Уже есть аккаунт? Авторизоваться</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock %}